package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	httptransport "github.com/go-swagger/go-swagger/httpkit/client"
	"github.com/go-swagger/go-swagger/spec"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/jawspeak/go-jira-restclient/client/operations"
)

// The Default jira rest API HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new jira rest API HTTP client.
func NewHTTPClient(formats strfmt.Registry) *JiraRestAPI {
	swaggerSpec, err := spec.New(SwaggerJSON, "")
	if err != nil {
		// the swagger spec is valid because it was used to generated this code.
		panic(err)
	}
	if formats == nil {
		formats = strfmt.Default
	}
	return New(httptransport.New(swaggerSpec), formats)
}

// New creates a new jira rest API client
func New(transport client.Transport, formats strfmt.Registry) *JiraRestAPI {
	cli := new(JiraRestAPI)
	cli.Transport = transport

	cli.Operations = operations.New(transport, formats)

	return cli
}

// JiraRestAPI is a client for jira rest API
type JiraRestAPI struct {
	Operations *operations.Client

	Transport client.Transport
}

// SetTransport changes the transport on the client and all its subresources
func (c *JiraRestAPI) SetTransport(transport client.Transport) {
	c.Transport = transport

	c.Operations.SetTransport(transport)

}
