package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*BadRequest bad request

swagger:model BadRequest
*/
type BadRequest struct {

	/* ErrorMessages error messages
	 */
	ErrorMessages []string `json:"errorMessages,omitempty"`

	/* Errors errors
	 */
	Errors map[string]string `json:"errors,omitempty"`
}

// Validate validates this bad request
func (m *BadRequest) Validate(formats strfmt.Registry) error {
	return nil
}
