package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*SearchResponse search response

swagger:model SearchResponse
*/
type SearchResponse struct {

	/* Expand expand
	 */
	Expand string `json:"expand,omitempty"`

	/* MaxResults max results
	 */
	MaxResults int64 `json:"maxResults,omitempty"`

	/* StartAt start at
	 */
	StartAt int64 `json:"startAt,omitempty"`

	/* total number in all pages
	 */
	Total int64 `json:"total,omitempty"`

	/* Values values
	 */
	Values []*Issue `json:"values,omitempty"`
}

// Validate validates this search response
func (m *SearchResponse) Validate(formats strfmt.Registry) error {
	return nil
}
