package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*User user

swagger:model User
*/
type User struct {

	/* Active active
	 */
	Active bool `json:"active,omitempty"`

	/* DisplayName display name
	 */
	DisplayName string `json:"displayName,omitempty"`

	/* EmailAddress email address
	 */
	EmailAddress string `json:"emailAddress,omitempty"`

	/* e.g. ldap username
	 */
	Key string `json:"key,omitempty"`

	/* e.g. ldap username
	 */
	Name string `json:"name,omitempty"`

	/* Self self
	 */
	Self string `json:"self,omitempty"`

	/* TimeZone time zone
	 */
	TimeZone string `json:"timeZone,omitempty"`
}

// Validate validates this user
func (m *User) Validate(formats strfmt.Registry) error {
	return nil
}
